---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	include = FALSE
)
library(magrittr)
library(ggplot2)

#unique(meso$name_meso)

# DADOS_INSTALACOES (POSSUI INFORMAÇÕES SOBRE A INSTALAÇÃO - INFORMAÇÕES GERAIS):
# - Código da instalação ("CPF da instalação")
# - Localização
# - Distribuidora
# - Fonte de Energia
# - Modalidade 

dados_instalacoes <- readr::read_csv2(file = 'dados_gd_05_24.csv')

# DADOS_INFO_TEC (POSSUI INFORMAÇÕES SOBRE A INSTALAÇÃO - ESPECÍFICAS SOBRE TÉCNICA)
# - Código da instalação ("CPF da instalação")
# - informações sobre fabricante e marca de placa
# - informações sobre fabricante e marca de inversor

dados_info_tec <- readr::read_csv2(file = 'dados_gd_info_05_24.csv')

municipios_mg <- geobr::read_municipality(code_muni = 'MG')

meso <- geobr::lookup_muni(code_muni = 'all') %>% 
  dplyr::filter(abbrev_state == 'MG') %>% 
  dplyr::select(code_muni,
                name_muni,
                code_meso,
                name_meso)

# municipios_mg %>% 
#   ggplot()+
#   geom_sf(mapping = aes())

info_geo <- dados_instalacoes %>% 
  janitor::clean_names() %>% 
  dplyr::filter(sig_uf == 'MG') %>% 
  dplyr::filter(sig_tipo_geracao == 'UFV') %>% 
  dplyr::select(cod_empreendimento,
                dth_atualiza_cadastral_empreend,
                cod_municipio_ibge,
                dsc_porte,
                dsc_classe_consumo,
                cod_sub_grupo_tarifario,
                dsc_modalidade_habilitado,
                qtd_uc_recebe_credito,
                mda_potencia_instalada_kw)

info_tec_geo <- dplyr::left_join(
  info_geo,
  dados_info_tec,
  by = c('cod_empreendimento' = 'CodGeracaoDistribuida')) %>% 
  janitor::clean_names() %>% 
  dplyr::select(-dat_geracao_conjunto_dados,
                -mda_area_arranjo,
                -mda_potencia_instalada,
                -dat_conexao,
                -mda_potencia_modulos,
                -mda_potencia_inversores,
                -qtd_modulos,
                -nom_modelo_modulo,
                -nom_modelo_inversor,
                -nom_fabricante_inversor) %>% 
  tidyr::drop_na()

fornecedores <- dplyr::left_join(
  info_tec_geo,
  meso,
  by = c('cod_municipio_ibge' = 'code_muni')
)

fornecedores_tratado <- fornecedores  %>% 
  dplyr::select(nom_fabricante_modulo,
                name_meso) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_to_upper(nom_fabricante_modulo)) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' SOLAR',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '- SOLAR',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'SOLAR',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' SOLLAR',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' BRASIL',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' POWER',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' TECNOLOGY',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'S/A',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' S/A',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'S/A ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'LTDA',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' LTDA',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'LTDA ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'LTD',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' LTD',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'LTD ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CO',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' CO',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CO ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' DO BRASIL',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' INC',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' -',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '- ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '-',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' ENERGY DO BRASIL',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' ENERGIA',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'ENERGY',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'ENERGIA',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CSI',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' DO',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'DO',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'ALTERNATIVE',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'BYD ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' BYD ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'NERGY',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'PAINEL',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' TECHNOLOGY',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'TECHNOLOGY',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = ' ENERGY',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'JA/ WEG',
      replacement = 'JA / WEG')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'JA',
      replacement = 'JA / WEG')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'JA / WEGYU',
      replacement = 'JA / WEG')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'JA / WEGM',
      replacement = 'JA / WEG')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '2JA / WEG',
      replacement = 'JA / WEG')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'JÁ',
      replacement = 'JA / WEG')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'JA / WEG / WEG',
      replacement = 'JA / WEG')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '4JA / WEG / WEG',
      replacement = 'JA / WEG')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'JA / WEG/WEG',
      replacement = 'JA / WEG')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'AE ',
      replacement = 'AE')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'RISEM',
      replacement = 'RISEN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'RISEN ',
      replacement = 'RISEN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'RIZEN',
      replacement = 'RISEN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'FVRISEN',
      replacement = 'RISEN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'Q.CELLS',
      replacement = 'QCELLS')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'QCELL',
      replacement = 'QCELLS')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'QCELLSS',
      replacement = 'QCELLS')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'AVPPROJECT',
      replacement = 'AVPROJECT')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'JYNKO',
      replacement = 'JINKO')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'JUNKO',
      replacement = 'JINKO')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'JINKOTIGERPRO',
      replacement = 'JINKO')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'JIN',
      replacement = 'JINKO')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'JINKOKO',
      replacement = 'JINKO')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANADIAN.',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANADIAN',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANADIANM',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANIDIAN',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANADIANNNC.',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANADIANNNC',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANADIANNC',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANADIANNC.',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANADIAN',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANADIA',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANDIAN',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANANDIAN',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'CANADIANN',
      replacement = 'CANADIAN')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'SUNNOVA',
      replacement = 'SUNOVA')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'AEG',
      replacement = 'AE')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'NÃO INFORMA',
      replacement = 'NAOINFORMA')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = 'INTELBRÁS',
      replacement = 'INTELBRAS')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '2',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '5',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '59 - ',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '20 - ',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '4 - ',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '10 - ',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '60 - ',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '2 - ',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '27 - ',
      replacement = '')) %>% 
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '116 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '1 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '49 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '181 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '63 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '7 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '6 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '68 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '56 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '65 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '108 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '51 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '46 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '183 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '68 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '57 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '11 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '66 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '9 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '0 - ',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '10',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '16',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '1',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '3',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '18',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '4',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '60',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '0',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '7',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '9',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '81',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '7',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '6',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '8',
      replacement = '')) %>%
  dplyr::mutate(
    nom_fabricante_modulo = stringr::str_replace(
      nom_fabricante_modulo,
      pattern = '1',
      replacement = '')) %>%
  table() %>% 
  as.data.frame()

fornecedores_triangulo <- fornecedores_tratado %>% 
  dplyr::filter(name_meso == "Triângulo Mineiro/Alto Paranaíba") %>%
  dplyr::top_n(1, wt = Freq) 

fornecedores_central <- fornecedores_tratado %>% 
  dplyr::filter(name_meso == "Central Mineira") %>%
  dplyr::top_n(1, wt = Freq) 

fornecedores_zm <- fornecedores_tratado %>% 
  dplyr::filter(name_meso == "Zona da Mata") %>%
  dplyr::top_n(1, wt = Freq)  

fornecedores_rio_doce <- fornecedores_tratado %>% 
  dplyr::filter(name_meso == "Vale do Rio Doce") %>%
  dplyr::top_n(1, wt = Freq)  

fornecedores_oeste_minas <- fornecedores_tratado %>% 
  dplyr::filter(name_meso == "Oeste de Minas") %>%
  dplyr::top_n(1, wt = Freq)  

fornecedores_mucuri <- fornecedores_tratado %>% 
  dplyr::filter(name_meso == "Vale do Mucuri") %>%
  dplyr::top_n(1, wt = Freq)  

fornecedores_norte <- fornecedores_tratado %>% 
  dplyr::filter(name_meso == "Norte de Minas") %>%
  dplyr::top_n(1, wt = Freq)  

fornecedores_sul_sudoeste <- fornecedores_tratado %>% 
  dplyr::filter(name_meso == "Sul/Sudoeste de Minas") %>%
  dplyr::top_n(1, wt = Freq)  

fornecedores_campo_vertentes <- fornecedores_tratado %>% 
  dplyr::filter(name_meso == "Campo das Vertentes") %>%
  dplyr::top_n(1, wt = Freq)  

fornecedores_jequitinhonha <- fornecedores_tratado %>% 
  dplyr::filter(name_meso == "Jequitinhonha") %>%
  dplyr::top_n(1, wt = Freq)  

fornecedores_bh <- fornecedores_tratado %>% 
  dplyr::filter(name_meso == "Metropolitana de Belo Horizonte") %>%
  dplyr::top_n(1, wt = Freq)  

fornecedores_noroeste <- fornecedores_tratado %>% 
  dplyr::filter(name_meso == "Noroeste de Minas") %>%
  dplyr::top_n(1, wt = Freq) 
  

fornecedores_geral_quadrado <- dplyr::bind_rows(
  fornecedores_central,
  fornecedores_triangulo,
  fornecedores_zm,
  fornecedores_rio_doce,
  fornecedores_oeste_minas,
  fornecedores_mucuri,
  fornecedores_norte,
  fornecedores_sul_sudoeste,
  fornecedores_campo_vertentes,
  fornecedores_jequitinhonha,
  fornecedores_bh,
  fornecedores_noroeste
) %>% 
  dplyr::mutate(name_meso = stringr::str_to_upper(name_meso)) 

meso_mapa <- geobr::read_meso_region(code_meso = 'MG') %>% 
  dplyr::mutate(name_meso = stringr::str_to_upper(name_meso)) %>%  
  dplyr::full_join(fornecedores_geral_quadrado,
                   by = c('name_meso' = 'name_meso')) %>% 
  ggplot()+
  geom_sf(mapping = aes(fill = Freq))+
  geom_sf_text(mapping = aes(label = nom_fabricante_modulo), color = 'white')

#quantidade em marca por meso região

#pensa que é blog, programação não importa muito.
#lixão tem vida útil. Qual o impacto da vida util do lixão 
# Há um proje de lei p transformar o modelus voltocaico em residuo elet. o resp é o fab. o resp pela log reversa.
#ent, esse post mostra quem sao os principais fab de modulos mais utilizados no estado de MG
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
meso_mapa
```

